### ISSUE TITLE
Code implementation

### ISSUE THREAD

**Issue by jis478** [bing-li-ai/AniGAN#4]
Hi, I've tried to implement according to your paper but no success. Would you please have a loot at my codes (https://github.com/jis478/AniGAN) and give me some directions on improving the results?

**Comment by oubathAI** [comment]
@jis478   I have try to implement it on my side with the same results as you; did you manage to have better results since you updated your github account?

@bing-li-ai Thanks for your nice paper, the results are really impressive. We understand if you don't want to share your trained model; but would you mind to share your training code to help us understand the exact implementation? 
Thanks!

**Comment by yl-zhu** [comment]
> @jis478 @oubathAI 
Hi, we have released the inference code. Our code borrows heavily from https://github.com/NVlabs/FUNIT. Replacing FUNIT G and D with AniGAN will significantly improve the effect.
